server:
  port: 8084

spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://postgres:5432/mobility
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j:
  circuitbreaker:
    instances:
      location:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      payment:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

app:
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_64_CHARS_MINIMUM________________}
